### PR TITLE
allow expansion of placeholders even if python not installed

### PR DESCRIPTION
**Pull request by adgitate1**
I would like to have `:Pandoc -o %:r.html` work if I don't have python installed.
#258

### CODE REVIEW

**Comment by fmoralesc** [comment]
Thanks, that's a good idea! Maybe we should avoid repeating code, and moving the expansions to a separate function. Wanna take a shot at it before we merge?

**Comment by adgitate1** [comment]
Oh. Good thinking. I will do that today.

**Comment by adgitate1** [comment]
Sorry for the delay. It is now updated. I will have another cool pull request coming soon.

**Comment by fmoralesc** [comment]
@adgitate1 Sorry for the delay in merging. Looks good! Thanks ;)

**Pull request merged**
