### PR TITLE
Fixed issue #133, caused by a regression in 7ffb061d283e9cbc20bf47f00…

### PR DESCRIPTION
**Pull request by INstinct42**
…8370e1e6a135686

### CODE REVIEW

**Comment by fmoralesc** [comment]
This will fail on pandoc 1.13, there there is a single *. I was going to
fix this, but my laptop locked up while building pandoc... If you can make
it catch both cases, it would be great.

**Comment by INstinct42** [comment]
Oh...
Ok, I see what I can do.

**Comment by INstinct42** [comment]
already found it, but thank you :)

**Comment by fmoralesc** [comment]
I merged it manually to squash the commits. Thanks a lot!

**Pull request closed without merging**
