### PR TITLE
Add support for coc.nvim

### PR DESCRIPTION
**Pull request by Freed-Wu**
See <https://github.com/neoclide/coc.nvim/wiki/Create-custom-source#start-by-a-simple-example>

### CODE REVIEW

**Comment by Freed-Wu** [comment]
image

**Comment by fmoralesc** [comment]
Thanks! This should probably go in the `vim-pandoc-after` repo, although the way the functions are loaded might need to be adjusted... @alerque, any thoughts?

**Comment by alerque** [comment]
Yes, this should go in the *after* plugin*. 

<sub>\* Long term I think most of that stuff should migrate back into this repository as autoload functions, but that's a topic and project for another day (and I have no immediate plans of working on it).</sub>

**Comment by fmoralesc** [comment]
That's exactly why I asked ;)

**Comment by carlosrojas** [comment]
I am sure someone could rewrite this better, but this might useful to others. This shows you the title when searching for the key.

```
function! coc#source#pandoc#init() abort
	return {
				\ 'priority': 9,
				\ 'shortcut': 'pandoc',
				\ 'filetypes': ['pandoc'],
				\ 'triggerCharacters': ['@'],
				\ }
endfunction

function! coc#source#pandoc#complete(opt, cb) abort
    let l:classes = []
	let l:items = []
	let l:bibs = split(glob('%:p:h/**/*.bib'))
	for l:bib in l:bibs
		let l:lines = readfile(l:bib)
		for l:line in l:lines
			if l:line =~# '^@.*{.*,'
				let l:items += [split(l:line, '{\|,')[1]]
            endif
            if l:line =~# '\st.*=.*{.*},'
                let l:items += [split(l:line, '{\|},')[1]]
			endif
		endfor
	endfor
	for count in range(0, len(l:items)-1, 2)
		call add(l:classes, {'word': l:items[count[0]], 'info': l:items[count[0]+1]})
	endfor
	call a:cb(l:classes)
endfunction

```

**Comment by Freed-Wu** [comment]
> I am sure someone could rewrite this better, but this might useful to others.

i think so, too. i am not good at coding. if i can help someone, i am glad. if someone can do better, i am glader.

**Comment by Freed-Wu** [comment]
@carlosrojas Can <https://github.com/oncomouse/coc-bibtex> works in your environment? it looks like a good plugin to provide bibtex completion for markdown, latex, etc. if it can work normally, we can use this plugin and close this PR!

**Pull request closed without merging**
