### PR TITLE
pandoc/command: fix comparisons in python calls

### PR DESCRIPTION
**Pull request by fmoralesc**
vint was overzealous before, it tried to lint python as viml

@alerque Do you know why vint caught these before? I couldn't reproduce locally.

### CODE REVIEW

**Comment by alerque** [comment]
I imagine that was _me_ being overzealous, not Vint. I had a `tmux` pane going with `vint` results being refreshed using `entr` as I was editing, but I was also visually flipping through instances of patterns faster that it was keeping up. I probably edited those lines of my own volition not realizing they were not the next line number on its list.

**Comment by fmoralesc** [comment]
I also imagined it could be something like that, but in any case I didn't caught these when I checked the PR either.

**Comment by alerque** [comment]
It's hard to backfill these kind of things in bulk and get it right. For example I guessed that most comparison operators _should_ be case sensitive unless I saw an obvious need for them to be insensitive. But with lint warnings happening on an ongoing basis it will be quite easy to get those kind of decisions right the first time.

**Comment by fmoralesc** [comment]
Exactly! Which is what was so brilliant about that idea.

**Pull request merged**
