### PR TITLE
allow --smart/-S to be passed with no arguments

### PR DESCRIPTION
**Pull request by NickHu**
It's broken otherwise

### CODE REVIEW

**Comment by fmoralesc** [comment]
You could maybe integrate this with the `--mathjax` code, so special cases like this are handled in a single block? Otherwise, LGTM. Thanks!

**Comment by NickHu** [comment]
I think it might be better to find the regression that caused this to stop working rather than trying to maintain lots of edge cases.

**Comment by fmoralesc** [comment]
I don't think it's a regression, but the pandoc command flags must have changed so the the argument parser is confused. The parser we have right now is not flexible enough. We discussed this on the issue concerning mathjax.

**Comment by NickHu** [comment]
I tried with an old checkout of vim-pandoc and it worked fine with the exact same pandoc flags

**Comment by fmoralesc** [comment]
Hm... I'll check that out, then. Anyway, will you make the changes I proposed, or will leave it as is? It's fine either way.

**Comment by alex-chew** [comment]
I think I found the regression and a fix for it; the PR is linked above. `PandocCommand` was adding an empty quoted token `""` during option translation, whenever an incoming option was just a flag (`val`/`opt[1]` was empty).

**Comment by fmoralesc** [comment]
Sure, that looks like it. Does it solve the issue, @NickHu?

**Comment by NickHu** [comment]
Can confirm that this issue is fixed.

**Pull request closed without merging**
